from docx import Document
from config import OUTPUT_DIR
import os

def create_approval_note(filename: str, title: str, findings: list[str], recommendation: str) -> str:
    doc = Document()
    doc.add_heading(title, level=1)

    doc.add_heading("Key Findings", level=2)
    for f in findings:
        doc.add_paragraph(f, style="List Bullet")

    doc.add_heading("Recommendation", level=2)
    doc.add_paragraph(recommendation)

    doc.add_paragraph("\nGenerated by Sovereign AI Workbench (on-premise, air-gapped).")

    path = os.path.join(OUTPUT_DIR, filename)
    doc.save(path)
    return path